# Generated by Django 5.1.7 on 2025-03-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_quiz_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='class_number',
            field=models.IntegerField(default=0),
        ),
    ]
